psst.tgz: psst.sh DashboardAPI.py apmon.py discover_CMSSW.sh export_siteconf_info.py ProcInfo.py Logger.py test_squid.py
	tar cvfz psst.tgz psst.sh DashboardAPI.py apmon.py discover_CMSSW.sh export_siteconf_info.py ProcInfo.py Logger.py test_squid.py

