psst.tgz: psst.sh \
		  exit_codes.txt \
		  reporting/DashboardAPI.py \
		  reporting/WMExceptions.py \
		  reporting/apmon.py \
		  reporting/ProcInfo.py \
		  reporting/Logger.py \
		  tests/check_siteconf.py \
		  tests/test_squid.py \
		  tests/check_proxy.sh \
		  tests/check_software_area.sh \
		  tests/check_os.sh \
		  tests/check_connection.sh \
		  tests/check_RPMs.sh \
		  tests/check_scratch_space.sh \
		  tests/get_required_packages.py \
		  tests/check_cpu_load.sh
	tar cvfz psst.tgz psst.sh \
			 		  exit_codes.txt \
					  reporting/DashboardAPI.py \
					  reporting/WMExceptions.py \
					  reporting/apmon.py \
					  reporting/ProcInfo.py \
					  reporting/Logger.py \
					  tests/check_siteconf.py \
					  tests/test_squid.py \
					  tests/check_proxy.sh \
					  tests/check_software_area.sh \
					  tests/check_os.sh \
					  tests/check_connection.sh \
					  tests/check_RPMs.sh \
					  tests/check_scratch_space.sh \
					  tests/get_required_packages.py \
					  tests/check_cpu_load.sh