psst.tgz: psst.sh \
		  exit_codes.txt \
		  psst_wrapper.sh \
		  reporting/es_report.py \
		  reporting/stomp \
		  tests/check_connection.sh \
		  tests/check_cpu_load.sh \
		  tests/check_software_area.sh \
		  tests/check_scratch_space.sh \
		  tests/check_proxy.sh \
		  tests/check_siteconf.py
	tar cvfz psst.tgz psst.sh \
					  exit_codes.txt \
					  psst_wrapper.sh \
					  reporting/es_report.py \
					  reporting/stomp \
					  tests/check_connection.sh \
					  tests/check_cpu_load.sh \
					  tests/check_software_area.sh \
					  tests/check_scratch_space.sh \
					  tests/check_proxy.sh \
					  tests/check_siteconf.py